/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2023-01-07 09:26:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.CODE_005fGRAPHY.html;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/CODE_GRAPHY/html/../include/header.jsp", Long.valueOf(1673080622378L));
    _jspx_dependants.put("/CODE_GRAPHY/html/../include/footer.jsp", Long.valueOf(1671816517869L));
    _jspx_dependants.put("/CODE_GRAPHY/html/../include/loginSession.jsp", Long.valueOf(1673080687909L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\" />\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("        <title>JOIN | 코드그라피(Code:graphy) 포트폴리오</title>\r\n");
      out.write("        <!-- 파비콘 -->\r\n");
      out.write("        <link rel=\"shortcut icon\" href=\"../images/common/favicon.ico\" />\r\n");
      out.write("        <!-- 회원가입 CSS -->\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"../css/join.css\" />\r\n");
      out.write("        <!-- 미디어쿼리 CSS -->\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"../css/media.css\">\r\n");
      out.write("        <!-- 제이쿼리 라이브러리 CDN -->\r\n");
      out.write("        <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js\"></script>\r\n");
      out.write("        <!-- 제이쿼리 UI CDN -->\r\n");
      out.write("        <script src=\"https://ajax.googleapis.com/ajax/libs/jqueryui/1.13.2/jquery-ui.min.js\"></script>\r\n");
      out.write("        <!-- 공통 -->\r\n");
      out.write("        <script src=\"../js/common.js\"></script>\r\n");
      out.write("        <!-- 로그인 JS -->\r\n");
      out.write("        <script src=\"../js/join.js\"></script>\r\n");
      out.write("    </head>\r\n");
      out.write("   <body>\r\n");
      out.write("    <!-- 로그인세션처리 인클루드 -->\r\n");
      out.write("    ");
      out.write('\r');
      out.write('\n');
 
/////////////////////////////////////////////////////////////
	// JSP 세션이 셋팅된 경우에 if문 중괄호 안이 표현됨
	if (session.getAttribute("name") != null) {
		// 중괄호열고 맨 아래 JSP코드블럭에 중괄호를 닫았음
		// 이 방법은 중간에 html,css,js를 그대로 코딩해서
		// 화면에 바로 출력 시키는 방법이다!(out.print로 출력시 복잡함!)
/////////////////////////////////////////////////////////////

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("  /*/////////////////////////////////////////////////\r\n");
      out.write("    함수명: loginSet\r\n");
      out.write("    기능: JSP코드에서 세션변수로 셋팅된 값을 화면에 반영한다\r\n");
      out.write("  *//////////////////////////////////////////////////\r\n");
      out.write("  function loginSet(auth){// msg-메시지, auto-권한\r\n");
      out.write("      // JSP에서 이 함수를 호출할 예정!\r\n");
      out.write("      // 따라서 내부의 실행코드는 html이 로딩된 후 실행해야함!\r\n");
      out.write("      // 그래서 반드시 제이쿼리 실행구역으로 싸줘야함!!!\r\n");
      out.write("      $(function(){ /// jQB //////////////////\r\n");
      out.write("\r\n");
      out.write("          // 2. 로그인 버튼 텍스트 변경\r\n");
      out.write("          // 대상: .login_title / LOGIN -> LOGOUT\r\n");
      out.write("            $(\".login_title\")\r\n");
      out.write("            .text(\"LOGOUT\")\r\n");
      out.write("\r\n");
      out.write("          // 3. 로그아웃 클릭시 로그아웃하기\r\n");
      out.write("          .click(function(){\r\n");
      out.write("              // 비동기통신으로 로그아웃 처리 페이지호출!\r\n");
      out.write("              // Ajax - $.post() 로 처리!\r\n");
      out.write("              // $.post(호출페이지, 전달변수셋팅, 콜백함수)\r\n");
      out.write("              $.post(\r\n");
      out.write("                // 1. 호출페이지\r\n");
      out.write("                  \"/CODE_GRAPHY/process/logout.jsp\",\r\n");
      out.write("                  // 2. 전달변수셋팅\r\n");
      out.write("                  {},\r\n");
      out.write("                  // 3. 콜백함수\r\n");
      out.write("                  function(res){// res-결과값\r\n");
      out.write("                    res = res.replace(/\\s/g,\"\");\r\n");
      out.write("                    console.log(\"실행결과:\", res);\r\n");
      out.write("                      if(res===\"ok\"){\r\n");
      out.write("\r\n");
      out.write("                          // 메시지\r\n");
      out.write("                          alert(\"로그아웃 되었습니다.\");                          \r\n");
      out.write("\r\n");
      out.write("                          // 첫페이지로 리로드\r\n");
      out.write("                          location.replace(\"/CODE_GRAPHY/html/index.jsp\");\r\n");
      out.write("                          \r\n");
      out.write("                      } ////// if ////////////////\r\n");
      out.write("                      else{\r\n");
      out.write("\r\n");
      out.write("                          // 메시지\r\n");
      out.write("                          alert(\"로그아웃시 문제가 발생하였습니다!\"+res);\r\n");
      out.write("\r\n");
      out.write("                      } ///// else ///////////////\r\n");
      out.write("                    \r\n");
      out.write("\r\n");
      out.write("                  } /// 콜백함수 ///////\r\n");
      out.write("\r\n");
      out.write("              );///////// Ajax - post /////////\r\n");
      out.write("          }) ///// click /////////////////////\r\n");
      out.write("          \r\n");
      out.write("        // 5. auth 권한 값이 \"A\"일 경우 \r\n");
      out.write("        // 관리자 페이지 아이콘 나타내기\r\n");
      out.write("        if (auth === \"A\" || auth === \"S\") {\r\n");
      out.write("            $(\".admin_title\").show()\r\n");
      out.write("            .click(()=>location.href=\"/CODE_GRAPHY/admin/list.jsp\");\r\n");
      out.write("                \r\n");
      out.write("        } /////////// if /////////////////\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      });////////// jQB //////////////////////\r\n");
      out.write("\r\n");
      out.write("  }////////// loginSet 함수 /////////////////////////\r\n");
      out.write("  //////////////////////////////////////////////////\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");


/////////////////////////////////////////////////////////////
String auth = session.getAttribute("auth").toString();
out.print("<script>loginSet('" + auth + "');</script>");


} /////// if //////////////
// 맨위에서 열어놓은 if문이 여기서 닫힘! 여기까지 세션셋팅시 출력됨!
////////////////////////////////////////////////////////////////

      out.write("\r\n");
      out.write("    <!-- 1. 헤더영역 -->\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"header\">\r\n");
      out.write("	<!-- 1-1. 데스크탑(DESKTOP) -->\r\n");
      out.write("	<div class=\"header ibx\">\r\n");
      out.write("		<div class=\"contents_box\">\r\n");
      out.write("			<!-- 1-1-0. 햄버거 버튼 -->\r\n");
      out.write("			<div class=\"ham\">\r\n");
      out.write("				<svg width=\"24px\" height=\"24px\" viewBox=\"0 0 24 24\" version=\"1.1\"\r\n");
      out.write("					xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("					xmlns:xlink=\"http://www.w3.org/1999/xlink\">\r\n");
      out.write("                            <title>Icons/24px/Menu</title>\r\n");
      out.write("                            <defs>\r\n");
      out.write("                                <path\r\n");
      out.write("						d=\"M11.0024554,18 C11.514032,18 11.9356655,18.3827202 11.9932888,18.8826674 L12,19 C12,19.5522847 11.5536886,20 11.0024554,20 L3.99754465,20 C3.44661595,20 3,19.5561352 3,19 C3,18.4477153 3.4463114,18 3.99754465,18 L11.0024554,18 Z M20.0066023,11 C20.5160523,11 20.935933,11.3827202 20.9933167,11.8826674 L21,12 C21,12.5522847 20.5550537,13 20.0066023,13 L3.99339768,13 C3.44475929,13 3,12.5561352 3,12 C3,11.4477153 3.44494629,11 3.99339768,11 L20.0066023,11 Z M20.0066023,4 C20.5160523,4 20.935933,4.38272018 20.9933167,4.88266744 L21,5 C21,5.55228475 20.5550537,6 20.0066023,6 L3.99339768,6 C3.44475929,6 3,5.55613518 3,5 C3,4.44771525 3.44494629,4 3.99339768,4 L20.0066023,4 Z\"\r\n");
      out.write("						id=\"path-1\"></path>\r\n");
      out.write("                            </defs>\r\n");
      out.write("                            <g stroke=\"none\" stroke-width=\"1\"\r\n");
      out.write("						fill=\"none\">\r\n");
      out.write("                                <mask id=\"mask-2\" fill=\"white\">\r\n");
      out.write("                                    <use xlink:href=\"#path-1\"></use>\r\n");
      out.write("                                </mask>\r\n");
      out.write("                                <use id=\"Combined-Shape\" fill=\"#000000\"\r\n");
      out.write("						fill-rule=\"nonzero\" xlink:href=\"#path-1\"></use>\r\n");
      out.write("                            </g>\r\n");
      out.write("                        </svg>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- 1-1-1. 로고 -->\r\n");
      out.write("			<div class=\"logo\">\r\n");
      out.write("				<a href=\"/CODE_GRAPHY/html/index.jsp\"> <img src=\"../images/common/main_logo.png\"\r\n");
      out.write("					alt=\"메인로고\" />\r\n");
      out.write("				</a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- 1-1-2. Global Navigation Bar -->\r\n");
      out.write("			<div class=\"GNB\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<!-- 상품 -->\r\n");
      out.write("					<li class=\"\"><a href=\"\"><span>SHOP</span></a> <!-- Local Navigation Bar -->\r\n");
      out.write("						<div class=\"LNB\">\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li><a href=\"\">BEST</a></li>\r\n");
      out.write("								<li><a href=\"\">OUTER</a></li>\r\n");
      out.write("								<li><a href=\"\">SET</a></li>\r\n");
      out.write("								<li><a href=\"\">PERTEX</a></li>\r\n");
      out.write("								<li><a href=\"\">TOP</a></li>\r\n");
      out.write("								<li><a href=\"\">BOTTOM</a></li>\r\n");
      out.write("								<li><a href=\"\">ACC</a></li>\r\n");
      out.write("								<li><a href=\"\">개인결제창</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div></li>\r\n");
      out.write("					<!-- 룩북 -->\r\n");
      out.write("					<li><a href=\"\"><span>LOOKBOOK</span></a></li>\r\n");
      out.write("					<!-- 매장찾기 -->\r\n");
      out.write("					<li><a href=\"/CODE_GRAPHY/html/aboutus.jsp\"><span>ABOUT US</span></a></li>\r\n");
      out.write("					<!-- 커뮤니티 -->\r\n");
      out.write("					<li class=\"\"><a href=\"\"><span>COMMUNITY</span></a> <!-- Local Navigation Bar -->\r\n");
      out.write("						<div class=\"LNB\">\r\n");
      out.write("							<ul>\r\n");
      out.write("								<li><a href=\"\">NOTICE</a></li>\r\n");
      out.write("								<li><a href=\"\">Q&A</a></li>\r\n");
      out.write("								<li><a href=\"\">REVIEW</a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- 1-1-3. TAB -->\r\n");
      out.write("		<ul class=\"tab_box\">\r\n");
      out.write("			<!-- 로그인 -->\r\n");
      out.write("			<li><a href=\"/CODE_GRAPHY/html/login.jsp\"><span class=\"login_title\">LOGIN</span></a></li>\r\n");
      out.write("			<!-- 관리자페이지 -->\r\n");
      out.write("			<li class=\"admin_title pc_admin\" style=\"height:80px; line-height:80px; cursor:pointer; display:none\">\r\n");
      out.write("				<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"#af231c\" class=\"bi bi-person-fill-gear\" viewBox=\"0 0 16 16\">\r\n");
      out.write("  					<path d=\"M11 5a3 3 0 1 1-6 0 3 3 0 0 1 6 0Zm-9 8c0 1 1 1 1 1h5.256A4.493 4.493 0 0 1 8 12.5a4.49 4.49 0 0 1 1.544-3.393C9.077 9.038 8.564 9 8 9c-5 0-6 3-6 4Zm9.886-3.54c.18-.613 1.048-.613 1.229 0l.043.148a.64.64 0 0 0 .921.382l.136-.074c.561-.306 1.175.308.87.869l-.075.136a.64.64 0 0 0 .382.92l.149.045c.612.18.612 1.048 0 1.229l-.15.043a.64.64 0 0 0-.38.921l.074.136c.305.561-.309 1.175-.87.87l-.136-.075a.64.64 0 0 0-.92.382l-.045.149c-.18.612-1.048.612-1.229 0l-.043-.15a.64.64 0 0 0-.921-.38l-.136.074c-.561.305-1.175-.309-.87-.87l.075-.136a.64.64 0 0 0-.382-.92l-.148-.045c-.613-.18-.613-1.048 0-1.229l.148-.043a.64.64 0 0 0 .382-.921l-.074-.136c-.306-.561.308-1.175.869-.87l.136.075a.64.64 0 0 0 .92-.382l.045-.148ZM14 12.5a1.5 1.5 0 1 0-3 0 1.5 1.5 0 0 0 3 0Z\"/>\r\n");
      out.write("				</svg>\r\n");
      out.write("			</li>\r\n");
      out.write("			<!-- MYPAGE -->\r\n");
      out.write("			<li>\r\n");
      out.write("				<a href=\"\">\r\n");
      out.write("					<svg class=\"svg-icon\" style=\"vertical-align: middle; fill: currentColor; overflow: hidden;\" viewBox=\"0 0 1024 1024\" version=\"1.1\" xmlns=\"http://www.w3.org/2000/svg\">\r\n");
      out.write("						<path d=\"M939.904 821.333A439.296 439.296 0 0 0 633.557 503.34a233.259 233.259 0 0 0 111.574-198.87C745.13 175.915 640.555 71.296 512 71.296S278.87 175.915 278.87 304.469a233.259 233.259 0 0 0 111.573 198.87A439.296 439.296 0 0 0 84.096 821.333a103.595 103.595 0 0 0 19.541 89.088c21.035 26.88 52.608 42.24 86.614 42.24h643.456a109.227 109.227 0 0 0 86.613-42.24c20.139-25.6 27.221-58.069 19.584-89.088zM330.069 304.47c0-100.352 81.622-181.973 181.931-181.973s181.93 81.621 181.93 181.973S612.353 486.4 512 486.4s-181.93-81.621-181.93-181.93z m549.974 574.422a59.307 59.307 0 0 1-46.336 22.613H190.25a59.307 59.307 0 0 1-46.336-22.613 52.096 52.096 0 0 1-10.155-45.312C176.725 659.328 332.245 537.6 512 537.6s335.275 121.728 378.197 295.979a52.053 52.053 0 0 1-10.154 45.312z\" />\r\n");
      out.write("					</svg>\r\n");
      out.write("				</a> \r\n");
      out.write("				<!-- Local Navigation Bar -->\r\n");
      out.write("				<div class=\"LNB\">\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><a href=\"\">ORDER LIST</a></li>\r\n");
      out.write("						<li><a href=\"\">PROFILE</a></li>\r\n");
      out.write("						<li><a href=\"\">COUPON LIST</a></li>\r\n");
      out.write("						<li><a href=\"\">MILEAGE</a></li>\r\n");
      out.write("						<li><a href=\"\">BOARD</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</li>\r\n");
      out.write("			<!-- 장바구니 -->\r\n");
      out.write("			<li>\r\n");
      out.write("				<a href=\"\">\r\n");
      out.write("					<svg aria-hidden=\"true\" class=\"pre-nav-design-icon\" focusable=\"false\" viewBox=\"0 0 24 24\" role=\"img\" width=\"24px\" height=\"24px\" fill=\"none\">\r\n");
      out.write("						<path stroke=\"currentColor\" stroke-width=\"1.5\" d=\"M8.25 8.25V6a2.25 2.25 0 012.25-2.25h3a2.25 2.25 0 110 4.5H3.75v8.25a3.75 3.75 0 003.75 3.75h9a3.75 3.75 0 003.75-3.75V8.25H17.5\"></path>\r\n");
      out.write("					</svg>\r\n");
      out.write("				</a>\r\n");
      out.write("			</li>\r\n");
      out.write("			<!-- 위시리스트 -->\r\n");
      out.write("			<li>\r\n");
      out.write("				<a href=\"\">\r\n");
      out.write("					<svg aria-hidden=\"true\" class=\"pre-nav-design-icon\" focusable=\"false\" viewBox=\"0 0 24 24\" role=\"img\" width=\"24px\" height=\"24px\" fill=\"none\">\r\n");
      out.write("						<path stroke=\"currentColor\" stroke-width=\"1.5\" d=\"M16.794 3.75c1.324 0 2.568.516 3.504 1.451a4.96 4.96 0 010 7.008L12 20.508l-8.299-8.299a4.96 4.96 0 010-7.007A4.923 4.923 0 017.205 3.75c1.324 0 2.568.516 3.504 1.451l.76.76.531.531.53-.531.76-.76a4.926 4.926 0 013.504-1.451\"></path>\r\n");
      out.write("					</svg>\r\n");
      out.write("				</a>\r\n");
      out.write("			</li>\r\n");
      out.write("			<!-- 검색창 -->\r\n");
      out.write("			<li class=\"sch\" style=\"height:80px; line-height:80px; cursor:pointer\">\r\n");
      out.write("				<svg class=\"svg-icon\" style=\"vertical-align: middle; fill: currentColor; overflow: hidden;\" viewBox=\"0 0 1024 1024\" version=\"1.1\" xmlns=\"http://www.w3.org/2000/svg\">\r\n");
      out.write("					<path d=\"M192 480a256 256 0 1 1 512 0 256 256 0 0 1-512 0m631.776 362.496l-143.2-143.168A318.464 318.464 0 0 0 768 480c0-176.736-143.264-320-320-320S128 303.264 128 480s143.264 320 320 320a318.016 318.016 0 0 0 184.16-58.592l146.336 146.368c12.512 12.48 32.768 12.48 45.28 0 12.48-12.512 12.48-32.768 0-45.28\" />\r\n");
      out.write("				</svg>\r\n");
      out.write("			</li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- 1-2. 모바일 LNB -->\r\n");
      out.write("	<div class=\"mobx\">\r\n");
      out.write("		<div class=\"mob_box\">\r\n");
      out.write("			<div class=\"mob_wrap\">\r\n");
      out.write("				<div class=\"mgnb\">\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><span>SHOP</span>\r\n");
      out.write("							<div class=\"mlnb\" style=\"display:none\">\r\n");
      out.write("								<ul>\r\n");
      out.write("									<li><a href=\"\">BEST</a></li>\r\n");
      out.write("									<li><a href=\"\">OUTER</a></li>\r\n");
      out.write("									<li><a href=\"\">SET</a></li>\r\n");
      out.write("									<li><a href=\"\">PERTEX</a></li>\r\n");
      out.write("									<li><a href=\"\">TOP</a></li>\r\n");
      out.write("									<li><a href=\"\">BOTTOM</a></li>\r\n");
      out.write("									<li><a href=\"\">ACC</a></li>\r\n");
      out.write("									<li><a href=\"\">개인결제창</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</div></li>\r\n");
      out.write("						<li><a href=\"\">LOOKBOOK</a></li>\r\n");
      out.write("						<li><a href=\"/CODE_GRAPHY/html/login.jsp\">ABOUT US</a></li>\r\n");
      out.write("						<li><span>COMMUNITY</span>\r\n");
      out.write("							<div class=\"mlnb\" style=\"display: none;\">\r\n");
      out.write("								<ul>\r\n");
      out.write("									<li><a href=\"\">NOTICE</a></li>\r\n");
      out.write("									<li><a href=\"\">Q&A</a></li>\r\n");
      out.write("									<li><a href=\"\">REVIEW</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</div></li>\r\n");
      out.write("						<li><span>MY</span>\r\n");
      out.write("							<div class=\"mlnb\" style=\"display: none;\">\r\n");
      out.write("								<ul>\r\n");
      out.write("									<li><a href=\"\">ORDER LIST</a></li>\r\n");
      out.write("									<li><a href=\"\">PROFILE</a></li>\r\n");
      out.write("									<li><a href=\"\">COUPON LIST</a></li>\r\n");
      out.write("									<li><a href=\"\">MILEAGE</a></li>\r\n");
      out.write("									<li><a href=\"\">BOARD</a></li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</div></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"mtab\">\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li class=\"admin_title mobile_admin\" style=\"color:red; display:none; font-size: 1.4rem; line-height: 28px; color: #af231c;\">관리자</li>\r\n");
      out.write("						<li><a href=\"/CODE_GRAPHY/html/login.jsp\" class=\"login_title\">로그인</a></li>\r\n");
      out.write("						<li><a href=\"/CODE_GRAPHY/html/join.jsp\">회원가입</a></li>\r\n");
      out.write("						<li><a href=\"\">장바구니</a></li>\r\n");
      out.write("						<li><a href=\"\">찜하기</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- 1-3. 검색창 -->\r\n");
      out.write("	<div class=\"sch_area\">\r\n");
      out.write("		<div class=\"sch_cover\"></div>\r\n");
      out.write("		<div class=\"sch_boxs\">\r\n");
      out.write("			<form action=\"/CODE_GRAPHY/html/search.jsp\">\r\n");
      out.write("				<div class=\"sch_box\">\r\n");
      out.write("					<input id=\"search\" name=\"search\" type=\"text\" maxlength=\"25\"\r\n");
      out.write("						style=\"outline: 0;\"> <input id=\"sbtn\" name=\"submit\"\r\n");
      out.write("						type=\"submit\" value=\"\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"key_box\">\r\n");
      out.write("					<ul class=\"list\">\r\n");
      out.write("						<li><a href=\"\"># 헤비아우터</a></li>\r\n");
      out.write("						<li><a href=\"\"># 플리스</a></li>\r\n");
      out.write("						<li><a href=\"\"># 트레이닝셋업</a></li>\r\n");
      out.write("						<li><a href=\"\"># 하프집업</a></li>\r\n");
      out.write("						<li><a href=\"\"># 조거팬츠</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</form>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- 1-4. 위젯 레이어 -->\r\n");
      out.write("	<div class=\"widget-layer\">\r\n");
      out.write("		<div class=\"util-btn\">\r\n");
      out.write("			<a href=\"\"><div class=\"find\"></div></a> <a\r\n");
      out.write("				href=\"https://pf.kakao.com/_CgIxjxb\" target=”_blank><div\r\n");
      out.write("					class=\"talk\"></div></a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"top-btn\">\r\n");
      out.write("			<div class=\"top\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("    <!-- 2.메인영역 -->\r\n");
      out.write("    <div id=\"main\">\r\n");
      out.write("        <div class=\"main\">\r\n");
      out.write("           <div class=\"signUp_box\">\r\n");
      out.write("                <div class=\"signUp\">\r\n");
      out.write("                    <!-- 제목 -->\r\n");
      out.write("                    <div class=\"tit\">JOIN</div>\r\n");
      out.write("                    <!-- 회원가입 폼 -->\r\n");
      out.write("                    <form action=\"../process/ins.jsp\" method=\"post\" class=\"logF\">\r\n");
      out.write("                        <!-- 아이디 -->\r\n");
      out.write("                        <div class=\"minput\">\r\n");
      out.write("                            <label for=\"mid\">아이디 (필수)</label>\r\n");
      out.write("                            <input type=\"text\" name=\"mid\" id=\"mid\">\r\n");
      out.write("                            <p class=\"error\"></p>\r\n");
      out.write("                            <p class=\"text\"> (영문소문자/숫자, 4~16자)</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- 비밀번호 -->\r\n");
      out.write("                        <div class=\"minput\">\r\n");
      out.write("                            <label for=\"mpw\">비밀번호 (필수)</label>\r\n");
      out.write("                            <div class=\"tooltip_wrap\">\r\n");
      out.write("                                <input type=\"password\" name=\"mpw\" id=\"mpw\" maxlength=\"16\">\r\n");
      out.write("                                <!-- 툴팁 -->\r\n");
      out.write("                                <div class=\"tooltip\">\r\n");
      out.write("                                    <div class=\"content\">\r\n");
      out.write("                                        <strong>※ 비밀번호 입력 조건</strong>\r\n");
      out.write("                                        <div class=\"warntxt\">\r\n");
      out.write("                                            - 대소문자/숫자/특수문자 중 2가지 이상 조합, 8자~16자\r\n");
      out.write("                                            <br>\r\n");
      out.write("                                            - 입력 가능 특수문자\r\n");
      out.write("                                            <br>\r\n");
      out.write("                                            &nbsp;&nbsp;&nbsp;  ~ ` ! @ # $ % ^ ( ) _ - = { } [ ] | ; : &lt; &gt; , . ? /\r\n");
      out.write("                                            <br>\r\n");
      out.write("                                            - 공백 입력 불가능\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"warn_close\"></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <p class=\"error\"></p>\r\n");
      out.write("                                <p class=\"text\"> (영문 대소문자/숫자/특수문자 중 2가지 이상 조합, 8자~16자)</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- 비밀번호 확인 -->\r\n");
      out.write("                        <div class=\"minput\">\r\n");
      out.write("                            <label for=\"mpw2\">비밀번호 확인 (필수)</label>\r\n");
      out.write("                            <input type=\"password\" name=\"mpw2\" id=\"mpw2\" maxlength=\"16\">\r\n");
      out.write("                            <p class=\"error\"></p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- 이름 -->\r\n");
      out.write("                        <div class=\"minput\">\r\n");
      out.write("                            <label for=\"mnm\">이름 (필수)</label>\r\n");
      out.write("                            <input type=\"text\" name=\"mnm\" id=\"mnm\" maxlength=\"20\">\r\n");
      out.write("                            <p class=\"error\"></p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"minput\">\r\n");
      out.write("                            <label for=\"phone\">휴대전화</label>\r\n");
      out.write("                            <input type=\"text\" name=\"phone\" id=\"phone\" maxlength=\"13\">\r\n");
      out.write("                            <p class=\"error\" style=\"display:block\"></p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"minput\">\r\n");
      out.write("                            <label for=\"email\">이메일 (필수)</label>\r\n");
      out.write("                            <input type=\"text\" name=\"email\" id=\"email\">\r\n");
      out.write("                            <p class=\"error\"></p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"btnbx\">\r\n");
      out.write("                            <p>＊ 선택항목은 입력하지 않거나 동의하지 않아도 회원 가입이 가능합니다.</p>\r\n");
      out.write("                            <input type=\"submit\" id=\"join_btn\" value=\"회원가입\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("           </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- 3. 푸터영역 -->\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"footer\">\r\n");
      out.write("	<!-- 3-1. 데스크탑(DESKTOP) -->\r\n");
      out.write("	<div class=\"footer ibx\">\r\n");
      out.write("		<div class=\"info1\">\r\n");
      out.write("			<div class=\"info_nav\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li><a href=\"\">이용약관</a></li>\r\n");
      out.write("					<li><a href=\"\">개인정보처리방침</a></li>\r\n");
      out.write("					<li><a href=\"\">FAQ</a></li>\r\n");
      out.write("					<li><a href=\"\">1:1문의</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"des\">\r\n");
      out.write("				<h1>COMPANY 콘트리트 웍스</h1>\r\n");
      out.write("				<p>회사주소 : 서울특별시 성동구 아차산로 66 (성수동2가) 4층(성수동2가, 대정빌딩)</p>\r\n");
      out.write("				<p>사업자등록번호 : 665-87-01689</p>\r\n");
      out.write("				<p>대표 : 채명석 전화번호 : 1833-9431 이메일문의 : cw@concreteworks.co.kr</p>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"copy\">\r\n");
      out.write("				<p>©CGP｜코드그라피(Code:graphy) All rights reserved.</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"info2\">\r\n");
      out.write("			<h1>1833-9431</h1>\r\n");
      out.write("			<span> MON-FRI 10:00 ~ 17:00 <br /> LUNCH 12:00 ~ 13:30 <br />\r\n");
      out.write("				주말, 공휴일 제외\r\n");
      out.write("			</span>\r\n");
      out.write("			<p>우리은행 1005-904-386101</p>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- 3-2. 모바일(MOBILE) -->\r\n");
      out.write("	<div class=\"footer_mob\">\r\n");
      out.write("		<div class=\"info1\">\r\n");
      out.write("			<div class=\"info_nav\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li><a href=\"\">이용약관</a></li>\r\n");
      out.write("					<li><a href=\"\">개인정보처리방침</a></li>\r\n");
      out.write("					<li><a href=\"\">FAQ</a></li>\r\n");
      out.write("					<li><a href=\"\">1:1문의</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"info2\">\r\n");
      out.write("			<h1>1833-9431</h1>\r\n");
      out.write("			<span> MON-FRI 10:00 ~ 17:00 <br /> LUNCH 12:00 ~ 13:30 <br />\r\n");
      out.write("				주말, 공휴일 제외\r\n");
      out.write("			</span>\r\n");
      out.write("			<p>우리은행 1005-904-386101</p>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"info3\">\r\n");
      out.write("			<div class=\"des\">\r\n");
      out.write("				<h1>COMPANY 콘트리트 웍스</h1>\r\n");
      out.write("				<p>회사주소 : 서울특별시 성동구 아차산로 66 (성수동2가) 4층(성수동2가, 대정빌딩)</p>\r\n");
      out.write("				<p>사업자등록번호 : 665-87-01689</p>\r\n");
      out.write("				<p>대표 : 채명석 전화번호 : 1833-9431 이메일문의 : cw@concreteworks.co.kr</p>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"copy\">\r\n");
      out.write("				<p>©CGP｜코드그라피(Code:graphy) All rights reserved.</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("   </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
